[package]
name = "load_stl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
stl_io = "0.7.0"
embedded-gfx = {path = ".."}
